apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: utp23rr0f-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-52c91c065b.ki9p.p3.openshiftapps.com/rhtap/rhtap-qe:a0ba70e29a833ba3f8f0a0997c280a33eb7d9741@sha256:080123782432be83b586d82493f96a133c2424e489a7caaa7d36c6b1c7f246f4
          name: container-image
